### ISSUE TITLE
Unable to start diffy_web_1 / build frontend entirely

### ISSUE THREAD

**Issue by aeifr** [pbu88/diffy#36]
Used branch: current master

No modification what so ever.

Running command: `docker-compose up` 

Result:
```Starting diffy_db_1 ... done
Starting diffy_web_1 ... done
Attaching to diffy_db_1, diffy_web_1
db_1   | 2020-03-20T10:50:01.222+0000 I  CONTROL  [main] Automatically disabling TLS 1.0, to force-enable TLS 1.0 specify --sslDisabledProtocols 'none'
db_1   | 2020-03-20T10:50:01.229+0000 I  CONTROL  [initandlisten] MongoDB starting : pid=1 port=27017 dbpath=/data/db 64-bit host=bf0fd7986171
db_1   | 2020-03-20T10:50:01.230+0000 I  CONTROL  [initandlisten] db version v4.2.3
db_1   | 2020-03-20T10:50:01.230+0000 I  CONTROL  [initandlisten] git version: 6874650b362138df74be53d366bbefc321ea32d4
db_1   | 2020-03-20T10:50:01.230+0000 I  CONTROL  [initandlisten] OpenSSL version: OpenSSL 1.1.1  11 Sep 2018
db_1   | 2020-03-20T10:50:01.230+0000 I  CONTROL  [initandlisten] allocator: tcmalloc
db_1   | 2020-03-20T10:50:01.230+0000 I  CONTROL  [initandlisten] modules: none
db_1   | 2020-03-20T10:50:01.231+0000 I  CONTROL  [initandlisten] build environment:
db_1   | 2020-03-20T10:50:01.231+0000 I  CONTROL  [initandlisten]     distmod: ubuntu1804
db_1   | 2020-03-20T10:50:01.231+0000 I  CONTROL  [initandlisten]     distarch: x86_64
db_1   | 2020-03-20T10:50:01.231+0000 I  CONTROL  [initandlisten]     target_arch: x86_64
db_1   | 2020-03-20T10:50:01.231+0000 I  CONTROL  [initandlisten] options: { net: { bindIp: "*" } }
db_1   | 2020-03-20T10:50:01.232+0000 I  STORAGE  [initandlisten] Detected data files in /data/db created by the 'wiredTiger' storage engine, so setting the active storage engine to 'wiredTiger'.
web_1  | npm ERR! path /diffy/frontend/package.json
web_1  | npm ERR! code ENOENT
web_1  | npm ERR! errno -2
web_1  | npm ERR! syscall open
web_1  | npm ERR! enoent ENOENT: no such file or directory, open '/diffy/frontend/package.json'
web_1  | npm ERR! enoent This is related to npm not being able to find a file.
web_1  | npm ERR! enoent
web_1  |
web_1  | npm ERR! A complete log of this run can be found in:
web_1  | npm ERR!     /root/.npm/_logs/2020-03-20T10_50_02_287Z-debug.log
diffy_web_1 exited with code 254
db_1   | 2020-03-20T10:50:01.232+0000 I  STORAGE  [initandlisten] wiredtiger_open config: create,cache_size=256M,cache_overflow=(file_max=0M),session_max=33000,eviction=(threads_min=4,threads_max=4),config_base=false,statistics=(fast),log=(enabled=true,archive=true,path=journal,compressor=snappy),file_manager=(close_idle_time=100000,close_scan_interval=10,close_handle_minimum=250),statistics_log=(wait=0),verbose=[recovery_progress,checkpoint_progress],
db_1   | 2020-03-20T10:50:02.543+0000 I  STORAGE  [initandlisten] WiredTiger message [1584701402:543475][1:0x7fbc70247b00], txn-recover: Recovering log 7 through 8
db_1   | 2020-03-20T10:50:02.669+0000 I  STORAGE  [initandlisten] WiredTiger message [1584701402:669945][1:0x7fbc70247b00], txn-recover: Recovering log 8 through 8
db_1   | 2020-03-20T10:50:02.694+0000 I  STORAGE  [initandlisten] WiredTiger message [1584701402:694480][1:0x7fbc70247b00], txn-recover: Main recovery loop: starting at 7/6144 to 8/256
db_1   | 2020-03-20T10:50:02.753+0000 I  STORAGE  [initandlisten] WiredTiger message [1584701402:753333][1:0x7fbc70247b00], txn-recover: Recovering log 7 through 8
db_1   | 2020-03-20T10:50:02.796+0000 I  STORAGE  [initandlisten] WiredTiger message [1584701402:796863][1:0x7fbc70247b00], txn-recover: Recovering log 8 through 8
db_1   | 2020-03-20T10:50:02.823+0000 I  STORAGE  [initandlisten] WiredTiger message [1584701402:823577][1:0x7fbc70247b00], txn-recover: Set global recovery timestamp: (0, 0)
db_1   | 2020-03-20T10:50:02.844+0000 I  RECOVERY [initandlisten] WiredTiger recoveryTimestamp. Ts: Timestamp(0, 0)
db_1   | 2020-03-20T10:50:02.865+0000 I  STORAGE  [initandlisten] Timestamp monitor starting
db_1   | 2020-03-20T10:50:02.869+0000 I  CONTROL  [initandlisten]
db_1   | 2020-03-20T10:50:02.870+0000 I  CONTROL  [initandlisten] ** WARNING: Access control is not enabled for the database.
db_1   | 2020-03-20T10:50:02.870+0000 I  CONTROL  [initandlisten] **          Read and write access to data and configuration is unrestricted.
db_1   | 2020-03-20T10:50:02.870+0000 I  CONTROL  [initandlisten]
db_1   | 2020-03-20T10:50:02.880+0000 I  SHARDING [initandlisten] Marking collection local.system.replset as collection version: <unsharded>
db_1   | 2020-03-20T10:50:02.898+0000 I  STORAGE  [initandlisten] Flow Control is enabled on this deployment.
db_1   | 2020-03-20T10:50:02.899+0000 I  SHARDING [initandlisten] Marking collection admin.system.roles as collection version: <unsharded>
db_1   | 2020-03-20T10:50:02.900+0000 I  SHARDING [initandlisten] Marking collection admin.system.version as collection version: <unsharded>
db_1   | 2020-03-20T10:50:02.907+0000 I  SHARDING [initandlisten] Marking collection local.startup_log as collection version: <unsharded>
db_1   | 2020-03-20T10:50:02.908+0000 I  FTDC     [initandlisten] Initializing full-time diagnostic data capture with directory '/data/db/diagnostic.data'
db_1   | 2020-03-20T10:50:02.915+0000 I  SHARDING [LogicalSessionCacheRefresh] Marking collection config.system.sessions as collection version: <unsharded>
db_1   | 2020-03-20T10:50:02.915+0000 I  SHARDING [LogicalSessionCacheReap] Marking collection config.transactions as collection version: <unsharded>
db_1   | 2020-03-20T10:50:02.918+0000 I  NETWORK  [listener] Listening on /tmp/mongodb-27017.sock
db_1   | 2020-03-20T10:50:02.918+0000 I  NETWORK  [listener] Listening on 0.0.0.0
db_1   | 2020-03-20T10:50:02.918+0000 I  NETWORK  [listener] waiting for connections on port 27017
```

NPM Logs when building frontend:
```0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'build'
1 verbose cli ]
2 info using npm@6.13.4
3 info using node@v12.16.1
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle diffy@1.0.0~prebuild: diffy@1.0.0
6 info lifecycle diffy@1.0.0~build: diffy@1.0.0
7 verbose lifecycle diffy@1.0.0~build: unsafe-perm in lifecycle true
8 verbose lifecycle diffy@1.0.0~build: PATH: PATH
9 verbose lifecycle diffy@1.0.0~build: CWD: C:\...\diffy\backend
10 silly lifecycle diffy@1.0.0~build: Args: [ '/d /s /c', 'rm -r dist;tsc' ]
11 silly lifecycle diffy@1.0.0~build: Returned: code: 1  signal: null
12 info lifecycle diffy@1.0.0~build: Failed to exec build script
13 verbose stack Error: diffy@1.0.0 build: `rm -r dist;tsc`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:311:20)
13 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:311:20)
13 verbose stack     at maybeClose (internal/child_process.js:1021:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
14 verbose pkgid diffy@1.0.0
15 verbose cwd C:\...\diffy\backend
16 verbose Windows_NT 10.0.17763
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "build"
18 verbose node v12.16.1
19 verbose npm  v6.13.4
20 error code ELIFECYCLE
21 error errno 1
22 error diffy@1.0.0 build: `rm -r dist;tsc`
22 error Exit status 1
23 error Failed at the diffy@1.0.0 build script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by pbu88** [comment]
Hey @aeifr , I'll take a look into this as soon as I can find some time. Thanks for reporting.

**Comment by markwbrown** [comment]
hey @aeifr [PR here](https://github.com/pbu88/diffy/pull/91) addresses this issue
